### PR TITLE
Fix warning in ExceptionReporter

### PR DESCRIPTION
**Pull request by mika-iriarte**
In some cases "ExceptionReporter" generates warning and Sentry class capture that warning and send to Sentry server.

### CODE REVIEW

**Comment by mindplay-dk** [comment]
Those lines are already using the `@` error suppression operator, which your error-handler should respect - see [this related question/answer on StackOverflow](https://stackoverflow.com/a/53957701/283851).

Check the README and Have a look at your `set_error_handler` function?

Nothing gets logged to Sentry unless you call `captureException`.

**Comment by mika-iriarte** [comment]
I copied `set_error_handler` from README
```
        set_error_handler(
            function ($severity, $message, $file, $line) {
                $error = new ErrorException($message, 0, $severity, $file, $line);
                if ($severity & (E_ALL & ~E_NOTICE & ~E_WARNING))
                    throw $error;
                else
                    self::$sentry->captureException($error);
        });
```
any `$sentry->captureException` leads to 
```
ErrorException: Undefined index: function
#9 vendor/kodus/sentry/src/Extensions/ExceptionReporter.php(187): null
```
and I see it in Sentry UI.
If I add check `error_reporting()==0` then warning was ignored. Works, but looks like anti-pattern.

**Comment by mindplay-dk** [comment]
> If I add check `error_reporting()==0` then warning was ignored. Works, but looks like anti-pattern.

Not an anti-pattern as far as I'm aware?

I don't know of any other way to actually support the error-suppression operator.

The `if (error_reporting() === 0) return;` condition probably should have been in the example.

**Comment by mika-iriarte** [comment]
I mean I think good practice for checking array index before accessing value. Error suppression looks like ani-pattern.
`if (error_reporting() === 0) return;` helps and wokrs. Thank you.

**Comment by mindplay-dk** [comment]
Well, nested ternaries and duplicate expressions look equally like anti-patterns to me.

Probably what we should have done is use the `??` operator to explicitly provide `""` fallbacks.

Anyhow, I don't work there or maintain this library anymore, so I will let the current maintainers figure it out.

**Comment by thomasnordahl-dk** [comment]
I agree that using the error suppression operator should be avoided, so I'm up for changing that.

I also have to agree that it's a bit much nesting of ternaries // conditionals for my taste, so I've made another solution here: https://github.com/kodus/sentry/pull/7 (part of our update for PHP 8 compatibility).

I apologize for the late response.

**Pull request closed without merging**
